Update rust-windows.yml

diff --git a/.github/workflows/rust-windows.yml b/.github/workflows/rust-windows.yml
--- a/.github/workflows/rust-windows.yml
+++ b/.github/workflows/rust-windows.yml
@@ -30,11 +30,18 @@ jobs:
           
     - name: Add MSYS2 to PATH
       shell: bash
-      run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
+      run: echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH
 
     - name: Set PKG_CONFIG_PATH
       run: echo "PKG_CONFIG_PATH=C:/msys64/mingw64/lib/pkgconfig" >> $GITHUB_ENV
-        
+    
+    - name: Check for pkg-config
+      shell: bash
+      run: |
+        which pkg-config || echo "pkg-config not found"
+        pkg-config --version || echo "pkg-config not working"
+        echo $PATH        
+    
     - name: Build
       shell: bash
       run: cargo build --verbose
